version: '3.4'
services:
    lightning-network.dnp.dappnode.eth:
        image: 'lightning-network.dnp.dappnode.eth:0.1.0'
        build: ./build
        volumes:
            - 'lndconfig_data:/root/.lnd/'
        ports:
            - '9735:9735'
        environment:
            - RPCUSER=dappnode
            - RPCPASS=dappnode
            - BITCOIND_HOST=my.bitcoin.dnp.dappnode.eth
            - NETWORK=mainnet
            - ALIAS=
            - EXT_IP=
volumes:
    lndconfig_data: {}
