version: '3.4'
services:
  lightning-network.dnp.dappnode.eth:
<<<<<<< HEAD
    image: 'lightning-network.dnp.dappnode.eth:0.1.1'
=======
    image: 'lightning-network.dnp.dappnode.eth:0.1.2'
>>>>>>> Bump versions, split backup
    build: ./build
    volumes:
      - 'lndconfig_data:/root/.lnd/'
    ports:
      - '9735:9735'
    environment:
      - RTL_PASSWORD=changeme
      - RPCUSER=dappnode
      - RPCPASS=dappnode
      - BITCOIND_HOST=my.bitcoin.dnp.dappnode.eth
      - NETWORK=mainnet
      - ALIAS=
      - 'COLOR=#5ACDC5'
      - EXT_IP=
volumes:
  lndconfig_data: {}
